[project]
name = "probabilistic_piping"
version = "0.0.5"
description = "Python package for probabilistic piping calculations"
channels = ["conda-forge"]
platforms = ["win-64", "linux-64", "osx-64"]
readme = "README.md"
license = "GPL-3.0"
license-file = "LICENSE"

[tasks]
# Installation
install = "pre-commit install"

# Docs
quartodoc-build = { cmd = "quartodoc build && rm objects.json", cwd = "docs" ,inputs = [
    "docs/_quarto.yml",
    "src/probabilistic_piping",
    ],outputs = [
    "docs/reference/"
    ]}
quarto-preview = { cmd = "export QUARTO_PYTHON=python && quarto preview docs", depends-on = [
    "quartodoc-build",
] }
quarto-check = { cmd = "quarto check all", depends-on = ["quartodoc-build"] }
quarto-render = { cmd = "export QUARTO_PYTHON=python && quarto render docs --to html --execute", depends-on = [
    "quartodoc-build",
] }
docs = { depends-on = ["quarto-preview"] }
pre-commit = "pre-commit run --all-files"


[feature.common.dependencies]
python = ">=3.11"
ipykernel ="*"
ipywidgets ="*"
matplotlib ="*"
nbclient ="*"
nbformat ="*"
numpy ="*"
openpyxl = ">=3.1.5"
openturns = ">=1.23,<2"
pandas ="*"
pre-commit = "*"
pytest ="*"
pytest-cov = "*"
quarto = ">=1.5.57"
quartodoc = ">=0.9.1"
ruff = ">=0.8.1"
tqdm = "*"

[feature.common.pypi-dependencies]
probabilistic_piping = { path = "src", editable = true }

[environments]
default = { features = ["common"] }
