project:
  type: website

website:
  title: "Probabilistic piping"
  navbar:
    left:
      - text: "Examples"
        menu:
          - examples/notebooks/introduction.ipynb
          - examples/notebooks/fixed_waterlevel.ipynb
          - examples/notebooks/prob_methods.ipynb
      - text: "Python API"
        file: reference/index.qmd
    right:
      - icon: github
        href: https://github.com/HKV-products-services/probabilistic_piping
        aria-label: GitHub
format:
  html:
    theme: cosmo
    toc: true

quartodoc:
  style: pkgdown
  dir: reference
  title: API Reference
  package: probabilistic_piping
  parser: numpy
  dynamic: True
  rewrite_all_pages: True
  options:
    include_inherited: true
    include_empty: true
    include_attributes: true
    include_classes: true
    include_functions: true
